homepage:
  path: /{_locale}
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  requirements:
    _locale: '%app_locales%'
  defaults:
    route: website_index
    _locale: '%locale%'
