index:
  path: '/'
  controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
  requirements:
    _locale: '%app_locales%'
  defaults:
    route: home_index
    _locale: '%locale%'
